[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.rez
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
